

trigger:
- main

pool: nitesh-wsl

stages:
  - stage: 'terraforminstallation'
    jobs:
      - job: 'terraforminstallation' 
        steps:
          - script: 'TfInstallation'
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: 'terraforminit'
    jobs: 
      - job: 'terraforminit' 
        steps:
          - script: 'init'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure-sc'
              backendAzureRmResourceGroupName: 'nitesh-rg'
              backendAzureRmStorageAccountName: 'stgnitesh'
              backendAzureRmContainerName: 'niteshcontainer'
              backendAzureRmKey: 'tfstatefile'
